title: Daniel Radunsky
logo: /assets/img/headshot.jpg
description: B.S. in Computational Data Sciences at Pennsylvania State University - University Park (College of Engineering) 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
