title: Daniel Radunsky
logo: /assets/img/new_headshot.jpg
description: B.S. in Computational Data Sciences at Pennsylvania State University - University Park (College of Engineering) 
show_downloads: false
google_analytics: 459519114
theme: jekyll-theme-minimal
