title: Daniel Radunsky
logo: /assets/img/headshot.jpg
description: Hi, my name is Daniel Radunsky. I am currently a student at Penn State University - University Park majoring in Computational Data Sciences in the College of Engineering with an expected graduation date of May, 2025.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
